run:
  skip-dirs:
    - testdata

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  golint:
    min-confidence: 0.1

linters:
    enable-all: true

issues:
    exclude-rules:
        -   text: "package comment should not have leading space"
            linters:
                - golint
                